const quotes: string[] = [
  "The only way to do great work is to love what you do. -SteveJobs",
  "Innovation distinguishes between a leader and a follower. -SteveJobs",
  "Your time is limited, so don't waste it living someone else's life. -SteveJobs",
  "Stay hungry, stay foolish. -SteveJobs",
  "The future belongs to those who believe in the beauty of their dreams. -EleanorRoosevelt",
  "It does not matter how slowly you go as long as you do not stop. -Confucius",
  "Everything you've ever wanted is on the other side of fear. -GeorgeAddair",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. -WinstonChurchill",
  "Hardships often prepare ordinary people for an extraordinary destiny. -CSLewis",
  "Believe you can and you're halfway there. -TheodoreRoosevelt",
  "I have not failed. I've just found 10,000 ways that won't work. -ThomasEdison",
  "Genius is one percent inspiration and ninety-nine percent perspiration. -ThomasEdison",
  "Don't watch the clock; do what it does. Keep going. -SamLevenson",
  "The secret of getting ahead is getting started. -MarkTwain",
  "It always seems impossible until it's done. -NelsonMandela",
  "Education is the most powerful weapon which you can use to change the world. -NelsonMandela",
  "Life is what happens when you're busy making other plans. -JohnLennon",
  "Get busy living or get busy dying. -StephenKing",
  "You only live once, but if you do it right, once is enough. -MaeWest",
  "In the end, it's not the years in your life that count. It's the life in your years. -AbrahamLincoln",
  "The many of life's failures are people who did not realize how close they were to success when they gave up. -ThomasEdison",
  "If you want to live a happy life, tie it to a goal, not to people or things. -AlbertEinstein",
  "Never let the fear of striking out keep you from playing the game. -BabeRuth",
  "Money and success don't change people; they merely amplify what is already there. -WillSmith",
  "Not how long, but how well you have lived is the main thing. -Seneca",
  "If life were predictable it would cease to be life, and be without flavor. -EleanorRoosevelt",
  "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it. -HenryFord",
  "In order to write about life first you must live it. -ErnestHemingway",
  "The big lesson in life, baby, is never be scared of anyone or anything. -FrankSinatra",
  "Sing like no one’s listening, love like you’ve never been hurt, dance like nobody’s watching. -SatchelPaige",
  "Everything negative - pressure, challenges - is all an opportunity for me to rise. -KobeBryant",
  "I like criticism. It makes you strong. -LeBronJames",
  "You never really learn much from hearing yourself speak. -GeorgeClooney",
  "Life imposes things on you that you can’t control, but you still have the choice of how you’re going to live through this. -CelineDion",
  "Life is never easy. There is work to be done and obligations to be met. -JohnFKennedy",
  "Live for each second without hesitation. -EltonJohn",
  "Life is like riding a bicycle. To keep your balance, you must keep moving. -AlbertEinstein",
  "Life is a succession of lessons which must be lived to be understood. -HelenKeller",
  "My mission in life is not merely to survive, but to thrive. -MayaAngelou",
  "You get what you give. -JenniferLopez",
  "Turn your wounds into wisdom. -OprahWinfrey",
  "The way I see it, if you want the rainbow, you gotta put up with  the rain. -DollyParton",
  "Do all the good you can, for all the people you can, in all the ways you can. -HillaryClinton",
  "Don’t settle for what life gives you; make life better and build something. -AshtonKutcher",
  "Everything comes to him who hustles while he waits. -ThomasEdison",
  "Every strike brings me closer to the next home run. -BabeRuth",
  "Dream big and dare to fail. -NormanVaughan",
  "Go confidently in the direction of your dreams! Live the life you've imagined. -HenryDavidThoreau",
  "Knowledge is power. -FrancisBacon",
  "Simplicity is the ultimate sophistication. -LeonardoDaVinci",
];
export const getRandomQuote = () => {
  return quotes[Math.floor(Math.random() * quotes.length)];
};
