export const pomodoroReminders: string[] = [
  "Stay focused, the end goal is worth it.",
  "Don't stop until you're proud.",
  "Your future self will thank you for this effort.",
  "Push yourself, because no one else is going to do it for you.",
  "Distractions are temporary, success is permanent.",
  "Work hard in silence, let your success be your noise.",
  "Focus on being productive instead of busy.",
  "Every minute counts. Make this session legendary.",
  "One task at a time. You’ve got this!",
  "The only way to finish is to start and stay.",
  "Deep breath in, deep breath out. Now, let’s focus.",
  "Small steps lead to big results.",
  "Progress over perfection.",
  "Be present in what you are doing right now.",
  "One Pomodoro at a time. Don't rush.",
  "Your mind is a powerful tool. Use it wisely.",
  "Clear your mind, focus your energy.",
  "It’s a marathon, not a sprint. Keep a steady pace.",
  "Focus is a muscle. You’re training it right now.",
  "Stay calm and stay on task.",
  "Focus on the journey, not the destination.",
  "Energy is the essence of life.",
  "Action is the foundational key to all success.",
  "The secret of getting ahead is getting started.",
  "A journey of a thousand miles begins with a single step.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Concentrate all your thoughts upon the work in hand.",
  "Where focus goes, energy flows.",
  "Great things are done by a series of small things brought together.",
  "Strive for greatness.",
  "Rome wasn't built in a day.",
  "Constant dropping wears away the stone.",
  "Diligence is the mother of good fortune.",
  "Better late than never, but never late is better.",
  "Early bird catches the worm.",
  "Eyes on the prize.",
  "Stay in the zone.",
  "Keep grinding.",
  "Zero distractions.",
  "Work mode: ON.",
  "Deep work only.",
  "Finish strong.",
  "Stay sharp.",
  "Focus, focus, focus.",
  "No excuses.",
  "Just do it.",
  "Make it happen.",
  "You're doing great.",
  "Stay disciplined.",
  "Almost there!",
];

export const getRandomReminder = () => {
  const randomIndex = Math.floor(Math.random() * pomodoroReminders.length);
  return pomodoroReminders[randomIndex];
};
